import type { NextPage } from "next";
import Head from "next/head";
import { useCallback, useEffect, useState } from "react";

const Home: NextPage = () => {
  const [valid, setValid] = useState(0);
  const [colors, setColors] = useState<string[]>([]);
  const [showMessage, setShowMessage] = useState(false);
  const [isWrongSelection, setIsWrongSelection] = useState(false);

  const generateColors = useCallback(
    () => {
      setColors([randomColor(), randomColor(), randomColor()]);
      setValid(Math.floor(Math.random() * 3));
    },
    [],
  )

  useEffect(() => {
    generateColors();
  }, [generateColors]);

  const randomColor = () => '#'+Math.floor(Math.random()*16777215).toString(16)

  const isGoodAnswer = (choice: number) => {
    setShowMessage(true);
    if (choice === valid) {
      setIsWrongSelection(false);
      generateColors();
    } else {
      setIsWrongSelection(true);
    }
  };

  if (colors.length < 3) {
    return <>Loading...</>;
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center">
        <Card bgColor={colors[valid] as string} />
        <div className="mt-10 flex w-96 justify-between">
          <button
            onClick={() => {
              isGoodAnswer(0);
            }}
            className="border-2 border-gray-700 bg-gray-300 px-5 py-1"
          >
            {colors[0]}
          </button>
          <button
            onClick={() => {
              isGoodAnswer(1);
            }}
            className="border-2 border-gray-700 bg-gray-300 px-5 py-1"
          >
            {colors[1]}
          </button>
          <button
            onClick={() => {
              isGoodAnswer(2);
            }}
            className="border-2 border-gray-700 bg-gray-300 px-5 py-1"
          >
            {colors[2]}
          </button>
        </div>
        <div className="mt-5">
          { showMessage ? <>
            { isWrongSelection ?
              <p className="text-red-600">Wrong color...</p> :
              <p className="text-green-600">Correct!</p>}
          </> :
          <p>Please choose a color</p>}
        </div>
      </main>
    </>
  );
};

export default Home;

type CardProps = {
  bgColor: string;
};

const Card = ({ bgColor }: CardProps) => {
  return (
    <section
      className="h-52 w-96"
      style={{ backgroundColor: bgColor }}
    ></section>
  );
};
